[package]
name = "structure"
edition = "2021"
description.workspace = true
authors.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
