[package]
name = "oktopus-wallet"
description = ""
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
rayon = { workspace = true }