name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo
      id: cache-cargo
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release

  lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo
      id: cache-cargo
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo
    - name: Formatting
      run: cargo fmt --all --check
    - name: Clippy
      run: cargo clippy --workspace -- -D warnings
    - name: Documentation
      run: cargo doc --no-deps --workspace --document-private-items
      env:
        RUSTDOCFLAGS: -D warnings
